# Generated by Django 5.1.4 on 2026-05-08 01:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_pageview_id_performancemetric_requestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('abandoned_at', models.DateTimeField(auto_now_add=True)),
                ('recovery_email_sent', models.BooleanField(default=False)),
                ('recovery_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovered', models.BooleanField(default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_order_id', models.IntegerField(blank=True, null=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('pages_visited', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'abandoned_carts',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_start', 'Checkout Start'), ('checkout_complete', 'Checkout Complete'), ('search', 'Search'), ('filter_applied', 'Filter Applied'), ('wishlist_add', 'Wishlist Add'), ('newsletter_signup', 'Newsletter Signup'), ('user_registration', 'User Registration'), ('user_login', 'User Login')], max_length=50)),
                ('session_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
            },
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitors', models.IntegerField(default=0)),
                ('product_views', models.IntegerField(default=0)),
                ('add_to_cart', models.IntegerField(default=0)),
                ('checkout_start', models.IntegerField(default=0)),
                ('checkout_complete', models.IntegerField(default=0)),
                ('visitor_to_view_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('view_to_cart_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_to_checkout_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('checkout_to_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversion_funnel',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_purchase', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('products_viewed', models.IntegerField(default=0)),
                ('customer_segment', models.CharField(choices=[('new', 'New Customer'), ('active', 'Active Customer'), ('at_risk', 'At Risk'), ('churned', 'Churned'), ('vip', 'VIP Customer')], default='new', max_length=50)),
                ('favorite_category', models.CharField(blank=True, max_length=100)),
                ('preferred_price_range', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_analytics',
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('add_to_cart_count', models.IntegerField(default=0)),
                ('wishlist_count', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('view_to_cart_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_to_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_analytics',
            },
        ),
        migrations.CreateModel(
            name='RevenueMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('website_visitors', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'revenue_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('search_count', models.IntegerField(default=0)),
                ('results_count', models.IntegerField(default=0)),
                ('click_through_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_analytics',
            },
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='PerformanceMetric',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='user',
        ),
        migrations.AddIndex(
            model_name='productanalytics',
            index=models.Index(fields=['date', 'revenue'], name='product_ana_date_a65911_idx'),
        ),
        migrations.AddIndex(
            model_name='productanalytics',
            index=models.Index(fields=['date', 'units_sold'], name='product_ana_date_56d721_idx'),
        ),
        migrations.AddIndex(
            model_name='productanalytics',
            index=models.Index(fields=['category_name', 'date'], name='product_ana_categor_4e37e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productanalytics',
            unique_together={('product_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['date', 'search_count'], name='search_anal_date_575d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['date', 'conversion_rate'], name='search_anal_date_62b7fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchanalytics',
            unique_together={('query', 'date')},
        ),
        migrations.DeleteModel(
            name='RequestLog',
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['abandoned_at'], name='abandoned_c_abandon_1258c3_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['user', 'abandoned_at'], name='abandoned_c_user_id_463616_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['recovered', 'abandoned_at'], name='abandoned_c_recover_9b5737_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_5b2eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_e_user_id_4d513c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id', 'timestamp'], name='analytics_e_session_b71835_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['product_id', 'timestamp'], name='analytics_e_product_aa2c0b_idx'),
        ),
    ]
