# Generated by Django 5.1.4 on 2026-05-08 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('bulk_update', 'Bulk Update'), ('bulk_delete', 'Bulk Delete'), ('export', 'Export'), ('import', 'Import'), ('login', 'Admin Login'), ('logout', 'Admin Logout'), ('permission_change', 'Permission Change'), ('system_config', 'System Configuration')], max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(default=dict, help_text='Field changes in {field: {old: value, new: value}} format')),
                ('affected_count', models.PositiveIntegerField(default=1, help_text='Number of objects affected')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='security_ad_user_id_b06486_idx'), models.Index(fields=['action_type', '-timestamp'], name='security_ad_action__f545ba_idx'), models.Index(fields=['content_type', '-timestamp'], name='security_ad_content_cbd207_idx'), models.Index(fields=['risk_level', '-timestamp'], name='security_ad_risk_le_0b7034_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('export', 'Export'), ('search', 'Search'), ('filter', 'Filter'), ('bulk_access', 'Bulk Access')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('record_count', models.PositiveIntegerField(default=1)),
                ('fields_accessed', models.JSONField(default=list, help_text='List of sensitive fields accessed')),
                ('purpose', models.CharField(blank=True, help_text='Business purpose for access', max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('query_params', models.JSONField(default=dict)),
                ('filters_applied', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='security_da_user_id_e77341_idx'), models.Index(fields=['model_name', '-timestamp'], name='security_da_model_n_511bf4_idx'), models.Index(fields=['access_type', '-timestamp'], name='security_da_access__2b1144_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked'), ('suspicious_activity', 'Suspicious Activity'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('brute_force_detected', 'Brute Force Detected'), ('admin_access', 'Admin Access'), ('permission_denied', 'Permission Denied'), ('data_export', 'Data Export'), ('sensitive_data_access', 'Sensitive Data Access')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='security_se_event_t_8d2050_idx'), models.Index(fields=['user', '-timestamp'], name='security_se_user_id_76ab6c_idx'), models.Index(fields=['ip_address', '-timestamp'], name='security_se_ip_addr_d55299_idx'), models.Index(fields=['severity', '-timestamp'], name='security_se_severit_88a96a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('malware_detected', 'Malware Detected'), ('ddos_attack', 'DDoS Attack'), ('privilege_escalation', 'Privilege Escalation'), ('suspicious_pattern', 'Suspicious Pattern'), ('policy_violation', 'Policy Violation')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('affected_systems', models.JSONField(default=list)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_country', models.CharField(blank=True, max_length=100)),
                ('attack_vector', models.CharField(blank=True, max_length=200)),
                ('response_actions', models.TextField(blank=True)),
                ('mitigation_steps', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status', '-detected_at'], name='security_se_status_736290_idx'), models.Index(fields=['severity', '-detected_at'], name='security_se_severit_627970_idx'), models.Index(fields=['incident_type', '-detected_at'], name='security_se_inciden_8529e3_idx')],
            },
        ),
    ]
