# Generated by Django 5.1.4 on 2026-05-06 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_add_sort_order_to_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('unique_queries', models.PositiveIntegerField(default=0)),
                ('zero_result_searches', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('anonymous_searches', models.PositiveIntegerField(default=0)),
                ('avg_result_count', models.FloatField(default=0.0)),
                ('avg_click_position', models.FloatField(default=0.0)),
                ('click_through_rate', models.FloatField(default=0.0)),
                ('top_queries', models.JSONField(blank=True, default=list)),
                ('top_zero_result_queries', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(db_index=True, max_length=255, unique=True)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_suggestions', to='products.category')),
            ],
            options={
                'ordering': ['-popularity', 'text'],
            },
        ),
        migrations.CreateModel(
            name='SearchClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_clicks', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='search_sear_query_5e9550_idx'), models.Index(fields=['product', 'created_at'], name='search_sear_product_166842_idx'), models.Index(fields=['user', 'created_at'], name='search_sear_user_id_771fa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('sort_applied', models.CharField(blank=True, max_length=50)),
                ('page_viewed', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='search_sear_query_62def4_idx'), models.Index(fields=['user', 'created_at'], name='search_sear_user_id_2836be_idx'), models.Index(fields=['result_count'], name='search_sear_result__794ea1_idx')],
            },
        ),
    ]
