# Generated by Django 4.2.16 on 2026-05-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_processedwebhookevent'),
        ('payments', '0002_rename_payments_stripe_pi_idx_payments_pa_stripe__6fe52c_idx_and_more'),
    ]

    operations = [
    ]
