# Generated by Django 5.1.4 on 2026-05-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_enterprise_variant_inventory'),
        ('products', '0008_add_sort_order_to_productimage'),
    ]

    operations = [
    ]
