# Generated by Django 5.1.4 on 2026-05-08 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20260508_0643'),
    ]

    operations = [
        # All DB columns already exist from previous partial migrations.
        # Use SeparateDatabaseAndState to sync Django state only.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='productvariant',
                    options={'ordering': ['size', 'color']},
                ),
                migrations.RenameIndex(
                    model_name='productvariant',
                    new_name='products_pr_sku_dcab68_idx',
                    old_name='products_pr_sku_idx',
                ),
                migrations.RenameIndex(
                    model_name='productvariant',
                    new_name='products_pr_stock_c72f45_idx',
                    old_name='products_pr_stock_idx',
                ),
                migrations.RenameIndex(
                    model_name='productvariant',
                    new_name='products_pr_is_acti_9d6315_idx',
                    old_name='products_pr_active_idx',
                ),
                migrations.AddField(
                    model_name='product',
                    name='average_rating',
                    field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                migrations.AddField(
                    model_name='product',
                    name='rating_distribution',
                    field=models.JSONField(default=dict, help_text='Distribution of ratings 1-5'),
                ),
                migrations.AddField(
                    model_name='product',
                    name='total_reviews',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='productvariant',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                    preserve_default=False,
                ),
            ],
        ),
    ]
